In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow.keras as keras

In [111]:
df = pd.read_csv('input_df_clustering.csv')

In [112]:
df = df.iloc[:, 1:]

In [113]:
df.columns = [f'vehicle_{col+1}' for col in range(20)]

In [114]:
df.columns

Index(['vehicle_1', 'vehicle_2', 'vehicle_3', 'vehicle_4', 'vehicle_5',
       'vehicle_6', 'vehicle_7', 'vehicle_8', 'vehicle_9', 'vehicle_10',
       'vehicle_11', 'vehicle_12', 'vehicle_13', 'vehicle_14', 'vehicle_15',
       'vehicle_16', 'vehicle_17', 'vehicle_18', 'vehicle_19', 'vehicle_20'],
      dtype='object')

In [115]:
df

,vehicle_1,vehicle_2,vehicle_3,vehicle_4,vehicle_5,vehicle_6,vehicle_7,vehicle_8,vehicle_9,vehicle_10,vehicle_11,vehicle_12,vehicle_13,vehicle_14,vehicle_15,vehicle_16,vehicle_17,vehicle_18,vehicle_19,vehicle_20
0,10.467719,7.400951,11.089528,10.470381,9.361345,5.691519,9.277579,4.294928,3.933131,2.972234,9.911619,11.329893,9.306845,9.877510,8.312581,10.488621,9.439255,10.096252,7.007507,10.515592
1,10.824309,8.079708,11.407747,11.020434,9.724464,6.196731,9.826991,4.657053,3.948430,3.311035,10.517452,12.284141,9.854541,10.596405,8.773826,10.952999,9.858707,10.698313,7.474041,11.355667
2,13.272013,9.221884,14.100175,13.223630,11.862999,7.106657,11.683209,5.367419,5.044312,3.674599,12.461973,14.150940,11.714581,12.380680,10.486311,13.270529,11.934716,12.707258,8.802571,13.147811
3,13.218159,9.367895,14.007743,13.247350,11.835154,7.212022,11.735769,5.440228,4.971332,3.765690,12.524072,14.337563,11.766206,12.497084,10.516113,13.258201,11.921749,12.762527,8.864946,13.299287
4,12.760569,9.238941,13.486117,12.863747,11.438171,7.098981,11.430666,5.347773,4.736796,3.745657,12.215819,14.100650,11.462924,12.237641,10.224877,12.840790,11.552765,12.436975,8.659468,13.061379
5,10.945955,8.524502,11.500130,11.299461,9.858878,6.514681,10.122691,4.879613,3.883832,3.538254,10.870846,12.892612,10.155274,11.025013,9.017726,11.164635,10.066398,11.038066,7.742582,11.891288
6,12.579813,9.091759,13.295511,12.670075,11.271673,6.984325,11.257799,5.262464,4.671422,3.683522,12.033872,13.878901,11.291163,12.048701,10.070721,12.652748,11.385950,12.250726,8.527038,12.858906
7,10.677699,8.483381,11.212251,11.109366,9.637135,6.478046,9.967703,4.843426,3.744204,3.539863,10.714009,12.800827,9.998062,10.903015,8.874183,10.940128,9.866983,10.872882,7.642971,11.791436
8,9.874049,8.109588,10.361356,10.406100,8.937819,6.179996,9.360625,4.606925,3.388263,3.410542,10.085110,12.190198,9.389659,10.312942,8.325963,10.192471,9.203642,10.223851,7.207650,11.209475
9,9.832776,8.040011,10.320954,10.349370,8.900454,6.131350,9.304578,4.572107,3.387125,3.378062,10.017309,12.092345,9.331678,10.240001,8.277924,10.141943,9.153450,10.157869,7.159997,11.120172
10,13.193287,9.400371,13.968901,13.236450,11.812556,7.230831,11.737254,5.453060,4.942919,3.787028,12.533960,14.376809,11.770031,12.516752,10.511713,13.241198,11.910801,12.768445,8.872903,13.332503
11,13.778242,9.580291,14.639097,13.734129,12.319787,7.384535,12.134370,5.577004,5.236412,3.818814,12.939866,14.699827,12.165347,12.860218,10.891265,13.779915,12.390304,13.194330,9.143062,13.655128
12,12.539607,9.063383,13.255867,12.638104,11.240028,6.966747,11.225961,5.248193,4.662501,3.671920,11.993729,13.835871,11.256827,12.012303,10.043569,12.616580,11.349143,12.214118,8.502006,12.817527
13,13.003779,9.277104,13.761592,13.041758,11.637945,7.130549,11.570035,5.377764,4.861184,3.739824,12.364768,14.185345,11.606328,12.345649,10.359266,13.048667,11.743379,12.590472,8.749468,13.156393
14,11.921933,8.840770,12.573705,12.117631,10.708711,6.786383,10.794976,5.102175,4.370116,3.614835,11.544683,13.452638,10.823375,11.620414,9.642760,12.051871,10.843164,11.748726,8.202514,12.439827
15,13.384040,9.467323,14.185873,13.404863,11.980305,7.288624,11.872691,5.498686,5.038892,3.802316,12.670377,14.493234,11.903899,12.636923,10.640138,13.419935,12.068029,12.913208,8.966029,13.446514
16,12.848082,9.237120,13.588801,12.923135,11.510538,7.100336,11.473662,5.351627,4.787463,3.734914,12.258569,14.110597,11.506321,12.263277,10.268369,12.912933,11.617224,12.482438,8.684244,13.077099
17,12.901355,9.193627,13.661694,12.947727,11.554345,7.073763,11.480100,5.334349,4.835326,3.704022,12.256093,14.060643,11.510717,12.242003,10.281994,12.950357,11.646873,12.486058,8.678314,13.037707
18,11.316844,8.602194,11.911766,11.595414,10.181951,6.590994,10.358306,4.945692,4.084910,3.545549,11.096324,13.049479,10.387166,11.215663,9.239830,11.492654,10.347694,11.281384,7.896573,12.049341
19,13.645845,9.590497,14.473470,13.637622,12.206248,7.384317,12.069587,5.573504,5.152635,3.841321,12.881054,14.694070,12.102982,12.827395,10.821670,13.666545,12.292016,13.128586,9.107640,13.640696

In [116]:
"""
side info:

            typical car speed : 13 - 30 m/s
"""

'\nside info:\n\n            typical car speed : 13 - 30 m/s\n'

In [117]:
def quantize_speeds(dataframe):
    """
    quantizes speeds for given dataframe to reduce computation

    returns: quantized dataframe
    """
    output_dataframe = pd.DataFrame()
    
    cols = dataframe.columns
    
    for col in cols:
        output_dataframe[col] = dataframe[col].round(decimals=3)
    
    return output_dataframe

In [118]:
def get_positions(dataframe):
    """
    calculates positions for each vehicle for the trip

    returns: positions dataframe
    """
    output_dataframe = pd.DataFrame()
    
    cols = dataframe.columns
    
    for col in cols:
        output_dataframe[col] = dataframe[col].cumsum()
    
    return output_dataframe

In [119]:
quantized_df = quantize_speeds(df)

In [120]:
quantized_df

,vehicle_1,vehicle_2,vehicle_3,vehicle_4,vehicle_5,vehicle_6,vehicle_7,vehicle_8,vehicle_9,vehicle_10,vehicle_11,vehicle_12,vehicle_13,vehicle_14,vehicle_15,vehicle_16,vehicle_17,vehicle_18,vehicle_19,vehicle_20
0,10.468,7.401,11.090,10.470,9.361,5.692,9.278,4.295,3.933,2.972,9.912,11.330,9.307,9.878,8.313,10.489,9.439,10.096,7.008,10.516
1,10.824,8.080,11.408,11.020,9.724,6.197,9.827,4.657,3.948,3.311,10.517,12.284,9.855,10.596,8.774,10.953,9.859,10.698,7.474,11.356
2,13.272,9.222,14.100,13.224,11.863,7.107,11.683,5.367,5.044,3.675,12.462,14.151,11.715,12.381,10.486,13.271,11.935,12.707,8.803,13.148
3,13.218,9.368,14.008,13.247,11.835,7.212,11.736,5.440,4.971,3.766,12.524,14.338,11.766,12.497,10.516,13.258,11.922,12.763,8.865,13.299
4,12.761,9.239,13.486,12.864,11.438,7.099,11.431,5.348,4.737,3.746,12.216,14.101,11.463,12.238,10.225,12.841,11.553,12.437,8.659,13.061
5,10.946,8.525,11.500,11.299,9.859,6.515,10.123,4.880,3.884,3.538,10.871,12.893,10.155,11.025,9.018,11.165,10.066,11.038,7.743,11.891
6,12.580,9.092,13.296,12.670,11.272,6.984,11.258,5.262,4.671,3.684,12.034,13.879,11.291,12.049,10.071,12.653,11.386,12.251,8.527,12.859
7,10.678,8.483,11.212,11.109,9.637,6.478,9.968,4.843,3.744,3.540,10.714,12.801,9.998,10.903,8.874,10.940,9.867,10.873,7.643,11.791
8,9.874,8.110,10.361,10.406,8.938,6.180,9.361,4.607,3.388,3.411,10.085,12.190,9.390,10.313,8.326,10.192,9.204,10.224,7.208,11.209
9,9.833,8.040,10.321,10.349,8.900,6.131,9.305,4.572,3.387,3.378,10.017,12.092,9.332,10.240,8.278,10.142,9.153,10.158,7.160,11.120
10,13.193,9.400,13.969,13.236,11.813,7.231,11.737,5.453,4.943,3.787,12.534,14.377,11.770,12.517,10.512,13.241,11.911,12.768,8.873,13.333
11,13.778,9.580,14.639,13.734,12.320,7.385,12.134,5.577,5.236,3.819,12.940,14.700,12.165,12.860,10.891,13.780,12.390,13.194,9.143,13.655
12,12.540,9.063,13.256,12.638,11.240,6.967,11.226,5.248,4.663,3.672,11.994,13.836,11.257,12.012,10.044,12.617,11.349,12.214,8.502,12.818
13,13.004,9.277,13.762,13.042,11.638,7.131,11.570,5.378,4.861,3.740,12.365,14.185,11.606,12.346,10.359,13.049,11.743,12.590,8.749,13.156
14,11.922,8.841,12.574,12.118,10.709,6.786,10.795,5.102,4.370,3.615,11.545,13.453,10.823,11.620,9.643,12.052,10.843,11.749,8.203,12.440
15,13.384,9.467,14.186,13.405,11.980,7.289,11.873,5.499,5.039,3.802,12.670,14.493,11.904,12.637,10.640,13.420,12.068,12.913,8.966,13.447
16,12.848,9.237,13.589,12.923,11.511,7.100,11.474,5.352,4.787,3.735,12.259,14.111,11.506,12.263,10.268,12.913,11.617,12.482,8.684,13.077
17,12.901,9.194,13.662,12.948,11.554,7.074,11.480,5.334,4.835,3.704,12.256,14.061,11.511,12.242,10.282,12.950,11.647,12.486,8.678,13.038
18,11.317,8.602,11.912,11.595,10.182,6.591,10.358,4.946,4.085,3.546,11.096,13.049,10.387,11.216,9.240,11.493,10.348,11.281,7.897,12.049
19,13.646,9.590,14.473,13.638,12.206,7.384,12.070,5.574,5.153,3.841,12.881,14.694,12.103,12.827,10.822,13.667,12.292,13.129,9.108,13.641

In [121]:
positions_df = get_positions(quantized_df)

In [122]:
positions_df

,vehicle_1,vehicle_2,vehicle_3,vehicle_4,vehicle_5,vehicle_6,vehicle_7,vehicle_8,vehicle_9,vehicle_10,vehicle_11,vehicle_12,vehicle_13,vehicle_14,vehicle_15,vehicle_16,vehicle_17,vehicle_18,vehicle_19,vehicle_20
0,10.468,7.401,11.090,10.470,9.361,5.692,9.278,4.295,3.933,2.972,9.912,11.330,9.307,9.878,8.313,10.489,9.439,10.096,7.008,10.516
1,21.292,15.481,22.498,21.490,19.085,11.889,19.105,8.952,7.881,6.283,20.429,23.614,19.162,20.474,17.087,21.442,19.298,20.794,14.482,21.872
2,34.564,24.703,36.598,34.714,30.948,18.996,30.788,14.319,12.925,9.958,32.891,37.765,30.877,32.855,27.573,34.713,31.233,33.501,23.285,35.020
3,47.782,34.071,50.606,47.961,42.783,26.208,42.524,19.759,17.896,13.724,45.415,52.103,42.643,45.352,38.089,47.971,43.155,46.264,32.150,48.319
4,60.543,43.310,64.092,60.825,54.221,33.307,53.955,25.107,22.633,17.470,57.631,66.204,54.106,57.590,48.314,60.812,54.708,58.701,40.809,61.380
5,71.489,51.835,75.592,72.124,64.080,39.822,64.078,29.987,26.517,21.008,68.502,79.097,64.261,68.615,57.332,71.977,64.774,69.739,48.552,73.271
6,84.069,60.927,88.888,84.794,75.352,46.806,75.336,35.249,31.188,24.692,80.536,92.976,75.552,80.664,67.403,84.630,76.160,81.990,57.079,86.130
7,94.747,69.410,100.100,95.903,84.989,53.284,85.304,40.092,34.932,28.232,91.250,105.777,85.550,91.567,76.277,95.570,86.027,92.863,64.722,97.921
8,104.621,77.520,110.461,106.309,93.927,59.464,94.665,44.699,38.320,31.643,101.335,117.967,94.940,101.880,84.603,105.762,95.231,103.087,71.930,109.130
9,114.454,85.560,120.782,116.658,102.827,65.595,103.970,49.271,41.707,35.021,111.352,130.059,104.272,112.120,92.881,115.904,104.384,113.245,79.090,120.250
10,127.647,94.960,134.751,129.894,114.640,72.826,115.707,54.724,46.650,38.808,123.886,144.436,116.042,124.637,103.393,129.145,116.295,126.013,87.963,133.583
11,141.425,104.540,149.390,143.628,126.960,80.211,127.841,60.301,51.886,42.627,136.826,159.136,128.207,137.497,114.284,142.925,128.685,139.207,97.106,147.238
12,153.965,113.603,162.646,156.266,138.200,87.178,139.067,65.549,56.549,46.299,148.820,172.972,139.464,149.509,124.328,155.542,140.034,151.421,105.608,160.056
13,166.969,122.880,176.408,169.308,149.838,94.309,150.637,70.927,61.410,50.039,161.185,187.157,151.070,161.855,134.687,168.591,151.777,164.011,114.357,173.212
14,178.891,131.721,188.982,181.426,160.547,101.095,161.432,76.029,65.780,53.654,172.730,200.610,161.893,173.475,144.330,180.643,162.620,175.760,122.560,185.652
15,192.275,141.188,203.168,194.831,172.527,108.384,173.305,81.528,70.819,57.456,185.400,215.103,173.797,186.112,154.970,194.063,174.688,188.673,131.526,199.099
16,205.123,150.425,216.757,207.754,184.038,115.484,184.779,86.880,75.606,61.191,197.659,229.214,185.303,198.375,165.238,206.976,186.305,201.155,140.210,212.176
17,218.024,159.619,230.419,220.702,195.592,122.558,196.259,92.214,80.441,64.895,209.915,243.275,196.814,210.617,175.520,219.926,197.952,213.641,148.888,225.214
18,229.341,168.221,242.331,232.297,205.774,129.149,206.617,97.160,84.526,68.441,221.011,256.324,207.201,221.833,184.760,231.419,208.300,224.922,156.785,237.263
19,242.987,177.811,256.804,245.935,217.980,136.533,218.687,102.734,89.679,72.282,233.892,271.018,219.304,234.660,195.582,245.086,220.592,238.051,165.893,250.904

In [123]:
fab_data=positions_df.copy()
fab_data=fab_data*2

In [124]:
fab_data

,vehicle_1,vehicle_2,vehicle_3,vehicle_4,vehicle_5,vehicle_6,vehicle_7,vehicle_8,vehicle_9,vehicle_10,vehicle_11,vehicle_12,vehicle_13,vehicle_14,vehicle_15,vehicle_16,vehicle_17,vehicle_18,vehicle_19,vehicle_20
0,20.936,14.802,22.180,20.940,18.722,11.384,18.556,8.590,7.866,5.944,19.824,22.660,18.614,19.756,16.626,20.978,18.878,20.192,14.016,21.032
1,42.584,30.962,44.996,42.980,38.170,23.778,38.210,17.904,15.762,12.566,40.858,47.228,38.324,40.948,34.174,42.884,38.596,41.588,28.964,43.744
2,69.128,49.406,73.196,69.428,61.896,37.992,61.576,28.638,25.850,19.916,65.782,75.530,61.754,65.710,55.146,69.426,62.466,67.002,46.570,70.040
3,95.564,68.142,101.212,95.922,85.566,52.416,85.048,39.518,35.792,27.448,90.830,104.206,85.286,90.704,76.178,95.942,86.310,92.528,64.300,96.638
4,121.086,86.620,128.184,121.650,108.442,66.614,107.910,50.214,45.266,34.940,115.262,132.408,108.212,115.180,96.628,121.624,109.416,117.402,81.618,122.760
5,142.978,103.670,151.184,144.248,128.160,79.644,128.156,59.974,53.034,42.016,137.004,158.194,128.522,137.230,114.664,143.954,129.548,139.478,97.104,146.542
6,168.138,121.854,177.776,169.588,150.704,93.612,150.672,70.498,62.376,49.384,161.072,185.952,151.104,161.328,134.806,169.260,152.320,163.980,114.158,172.260
7,189.494,138.820,200.200,191.806,169.978,106.568,170.608,80.184,69.864,56.464,182.500,211.554,171.100,183.134,152.554,191.140,172.054,185.726,129.444,195.842
8,209.242,155.040,220.922,212.618,187.854,118.928,189.330,89.398,76.640,63.286,202.670,235.934,189.880,203.760,169.206,211.524,190.462,206.174,143.860,218.260
9,228.908,171.120,241.564,233.316,205.654,131.190,207.940,98.542,83.414,70.042,222.704,260.118,208.544,224.240,185.762,231.808,208.768,226.490,158.180,240.500
10,255.294,189.920,269.502,259.788,229.280,145.652,231.414,109.448,93.300,77.616,247.772,288.872,232.084,249.274,206.786,258.290,232.590,252.026,175.926,267.166
11,282.850,209.080,298.780,287.256,253.920,160.422,255.682,120.602,103.772,85.254,273.652,318.272,256.414,274.994,228.568,285.850,257.370,278.414,194.212,294.476
12,307.930,227.206,325.292,312.532,276.400,174.356,278.134,131.098,113.098,92.598,297.640,345.944,278.928,299.018,248.656,311.084,280.068,302.842,211.216,320.112
13,333.938,245.760,352.816,338.616,299.676,188.618,301.274,141.854,122.820,100.078,322.370,374.314,302.140,323.710,269.374,337.182,303.554,328.022,228.714,346.424
14,357.782,263.442,377.964,362.852,321.094,202.190,322.864,152.058,131.560,107.308,345.460,401.220,323.786,346.950,288.660,361.286,325.240,351.520,245.120,371.304
15,384.550,282.376,406.336,389.662,345.054,216.768,346.610,163.056,141.638,114.912,370.800,430.206,347.594,372.224,309.940,388.126,349.376,377.346,263.052,398.198
16,410.246,300.850,433.514,415.508,368.076,230.968,369.558,173.760,151.212,122.382,395.318,458.428,370.606,396.750,330.476,413.952,372.610,402.310,280.420,424.352
17,436.048,319.238,460.838,441.404,391.184,245.116,392.518,184.428,160.882,129.790,419.830,486.550,393.628,421.234,351.040,439.852,395.904,427.282,297.776,450.428
18,458.682,336.442,484.662,464.594,411.548,258.298,413.234,194.320,169.052,136.882,442.022,512.648,414.402,443.666,369.520,462.838,416.600,449.844,313.570,474.526
19,485.974,355.622,513.608,491.870,435.960,273.066,437.374,205.468,179.358,144.564,467.784,542.036,438.608,469.320,391.164,490.172,441.184,476.102,331.786,501.808

In [125]:
# def get_clusters(dataframe, duration, cluster_radius, test_car = 'vehicle_1'):
#         """
#         clustering algorithm for offloading decision making

#         returns: optimal cluster formation for given test vehicle
#         """
#         pos_cluster = {test_car: {}}
        
#         position_test = dataframe[test_car][duration] #test vehicle position for ending timestep
        
#         x = dataframe.drop(columns=['vehicle_3']) 

#         all_pos_timestep = x.iloc[duration, :] #positions data for all other cars for ending timestep
                
#         vehicle_names = x.columns
        
#         for service_veh in range(len(all_pos_timestep)):
#             diff = abs(all_pos_timestep[service_veh] - position_test)
            
#             if diff < cluster_radius:
#                 if round(diff, 2) != 0.0:
#                     pos_cluster[test_car][vehicle_names[service_veh]] = round(diff, 2)

#         return pos_cluster

In [126]:
# print(272.8-268.13)
# print(300.6-319.11)
# print(333.95-353.56)
# print(368-384.91)

In [171]:
class Cluster:
    
    def quantize_speeds(self, dataframe):
        """
        quantizes speeds for given dataframe to reduce computation

        returns: quantized dataframe
        """
        output_dataframe = pd.DataFrame()

        cols = dataframe.columns

        for col in cols:
            output_dataframe[col] = dataframe[col].round(decimals=3)

        return output_dataframe
   
    def get_positions(self, dataframe):
        """
        calculates positions for each vehicle for the trip

        returns: positions dataframe
        """
        output_dataframe = pd.DataFrame()

        cols = dataframe.columns

        for col in cols:
            output_dataframe[col] = dataframe[col].cumsum()

        return output_dataframe


    def get_clusters(self, dataframe, duration, cluster_radius, test_car):
        """
        clustering algorithm for offloading decision making

        returns: optimal cluster formation for given test vehicle
        """
#         drop_car=self.test_car  #ya wala dekh
        pos_cluster = {test_car: {}}
        
        position_test = dataframe[test_car][duration] #test vehicle position for ending timestep
        
        x = dataframe.drop(columns=[test_car]) 

        all_pos_timestep = x.iloc[duration, :] #positions data for all other cars for ending timestep
                
        vehicle_names = x.columns
        
        for service_veh in range(len(all_pos_timestep)):
            diff = abs(all_pos_timestep[service_veh] - position_test)
            
            if diff < cluster_radius:
                if round(diff, 2) != 0.0:
                    pos_cluster[test_car][vehicle_names[service_veh]] = round(diff, 2)

        return pos_cluster
    
    def PBTO(self, distance, size):
        """
        computes time based on distance of service vehicle from test vehicle and the size of task in MBs

        returns: time for transmission, computation and retransmission
        """
        B = 10
        Pt = 0.5
        No = 10E-2
        S = Pt/(distance**2)
        SNR = S/No
        DR = B*np.log2(1+SNR)
        Txt = size/DR
        Cxt = 5
        Rxt = (size/5)/DR
        print(f'- Txt {Txt} - Cxt {Cxt} - Rxt {Rxt}')
        time = Txt + Cxt + Rxt
        
        
        return time    
    
    def selected_sorted_nearest_cars(self, vehicle):
    
        near_cars=get_clusters(fab_data,duration=1,cluster_radius=20,test_car=vehicle)
        sort_orders = sorted(near_cars[vehicle].items(), key=lambda x: x[1])

        names = []
        #select first four cars from list

        for i in range(4):
            name = sort_orders[i][0]
            names.append(name)
        return names
    

    def final_cars_availble(self, test_car, names, duration, dataframe):

        pos_cluster = {test_car: {}}

        position_test = dataframe[test_car][duration] #test vehicle position for ending timestep

        x = dataframe.drop(columns=[test_car]) 

        all_pos_timestep = x.iloc[duration, :] #positions data for all other cars for ending timestep

        vehicle_names = x.columns


        ending_distances = []
        times = []

        for service_veh in range(len(names)):
            diff = abs(all_pos_timestep[service_veh] - position_test)
            ending_distances.append(diff)

        for distance in ending_distances:
            times.append(self.PBTO(distance, 5))
        print("ending distances", ending_distances)
        mean = np.mean(times)

        print("\n\n",mean)
    

# acha wala
cluster_obj = Cluster()

quantized_df = cluster_obj.quantize_speeds(df)

positions_df = cluster_obj.get_positions(quantized_df)


clusters = cluster_obj.get_clusters(fab_data, duration=10, cluster_radius=50, test_car="vehicle_6")
# print(clusters)

distances = list(clusters[list(clusters.keys())[0]].values())

distances = sorted(distances)

if len(distances) >= 4:
    distances = distances[:4]

print(distances)
times = []

for distance in distances:
    times.append(cluster_obj.PBTO(distance,0.5))


mean = np.mean(times)
round(mean, 2)
# names = cluster_obj.selected_sorted_nearest_cars("vehicle_6")

# final_cars_availble('vehicle_6', names, 10, fab_data)

[30.27, 36.2, 44.27]
- Txt 6.368432734836363 - Cxt 5 - Rxt 1.2736865469672725
- Txt 9.100595593783822 - Cxt 5 - Rxt 1.8201191187567645
- Txt 13.601847810669547 - Cxt 5 - Rxt 2.7203695621339095

16.63

In [149]:
names = selected_sorted_nearest_cars("vehicle_6")

In [151]:
names = selected_sorted_nearest_cars("vehicle_6")
final_cars_availble('vehicle_6', names, 10, fab_data)

 885.7863807555553

In [42]:
# for item in clusters:
#     print(list(clusters[item].values()))

[22.13, 18.1, 26.18, 15.14]

In [34]:
clusters

{'vehicle_3': {'vehicle_4': 4.86, 'vehicle_20': 1.17}}

In [103]:
# def PBTO(distance, size):
#     # transmission time
#     B = 10
#     Pt = 0.5
#     No = 10E-10
#     S = Pt/ (distance**2)
#     SNR = S/No
#     DR = B*np.log2(1+SNR)
# #     print(f'data rate {DR}')
#     Txt = size/DR
#     Cxt = 5
#     Rxt = (size/5)/DR
#     time = Txt + Cxt + Rxt
#     return time

    
# # mean = np.mean(times)

In [104]:
# def get_clusters(dataframe, duration, cluster_radius, test_car):
#         """
#         clustering algorithm for offloading decision making

#         returns: optimal cluster formation for given test vehicle
#         """
# #         drop_car=self.test_car  #ya wala dekh
#         pos_cluster = {test_car: {}}
        
#         position_test = dataframe[test_car][duration] #test vehicle position for ending timestep
        
#         x = dataframe.drop(columns=[test_car]) 

#         all_pos_timestep = x.iloc[duration, :] #positions data for all other cars for ending timestep
                
#         vehicle_names = x.columns
        
#         for service_veh in range(len(all_pos_timestep)):
#             diff = abs(all_pos_timestep[service_veh] - position_test)
            
#             if diff < cluster_radius:
#                 if round(diff, 2) != 0.0:
#                     pos_cluster[test_car][vehicle_names[service_veh]] = round(diff, 2)

#         return pos_cluster



def selected_sorted_nearest_cars(vehicle):
    
    near_cars=get_clusters(fab_data,duration=1,cluster_radius=20,test_car=vehicle)
    sort_orders = sorted(near_cars[vehicle].items(), key=lambda x: x[1])
    
    names = []
    #select first four cars from list
    
    for i in range(4):
        name = sort_orders[i][0]
        names.append(name)
    return names


names = selected_sorted_nearest_cars("vehicle_6")



# now we can choose 2 or 3 cars according to our data

In [152]:
# imp

def final_cars_availble(test_car, names, duration, dataframe):
    
    pos_cluster = {test_car: {}}

    position_test = dataframe[test_car][duration] #test vehicle position for ending timestep

    x = dataframe.drop(columns=[test_car]) 

    all_pos_timestep = x.iloc[duration, :] #positions data for all other cars for ending timestep

    vehicle_names = x.columns
    

    ending_distances = []
    times = []
    
    for service_veh in range(len(names)):
        diff = abs(all_pos_timestep[service_veh] - position_test)
        ending_distances.append(diff)
        
    for distance in ending_distances:
        times.append(cluster_obj.PBTO(distance, 5))
    print(ending_distances)
    mean = np.mean(times)
    
    print("\n\n",mean)


final_cars_availble('vehicle_6', names, 10, fab_data)

[109.64199999999997, 44.26800000000003, 123.85000000000002, 114.13600000000002]


 885.7863807555553

In [ ]:
names = selected_sorted_nearest_cars("vehicle_6")
final_cars_availble('vehicle_6', names, 10, fab_data)

In [107]:
# def sorted_nearest_cars(vehicle,duration, cluster_radius, dataframe ):
    
#     cluster_radius_1 = 50
    
#     pos_cluster = {vehicle: {}}
        
#     position_test = dataframe[vehicle][0]  #test vehicle position for starting timestep

#     x = dataframe.drop(columns=[vehicle]) 

#     all_pos_timestep = x.iloc[0, :] #positions data for all other cars for ending timestep

#     for service_veh in range(len(all_pos_timestep)):
#         diff = abs(all_pos_timestep[service_veh] - position_test)

#     if diff < cluster_radius_1:
#             if round(diff, 2) != 0.0:
#                 pos_cluster[test_car][vehicle_names[service_veh]] = round(diff, 2)